replicaCount: 1

image:
  repository: gotify/server
  pullPolicy: IfNotPresent
  tag: "2.1"

serviceAccount:
  create: true

service:
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/target: homelab.terence.cloud
  hosts:
    - host: gotify.terence.cloud
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: gotify-tls
      hosts:
        - gotify.terence.cloud

envFrom:
  - configMapRef:
      name: gotify-env
  - secretRef:
      name: gotify-credentials

volumeMounts:
  - name: gotify-data
    mountPath: /app/data

volumes:
  - name: gotify-data
    persistentVolumeClaim:
      claimName: gotify-data

persistentVolumes:
  - name: gotify-data
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClassName: longhorn

configMaps:
  - name: gotify-env
    data:
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      TZ: "Europe/Paris"
      GOTIFY_SERVER_PORT: "80"
      GOTIFY_SERVER_KEEPALIVEPERIODSECONDS: "0"
      GOTIFY_SERVER_LISTENADDR: "0.0.0.0"
      GOTIFY_SERVER_SSL_ENABLED: "false"
      GOTIFY_SERVER_SSL_REDIRECTTOHTTPS: "true"
      GOTIFY_SERVER_SSL_LISTENADDR: ""
      GOTIFY_SERVER_SSL_PORT: "443"
      GOTIFY_SERVER_SSL_CERTFILE: ""
      GOTIFY_SERVER_SSL_CERTKEY: ""
      GOTIFY_SERVER_SSL_LETSENCRYPT_ENABLED: "false"
      GOTIFY_SERVER_SSL_LETSENCRYPT_ACCEPTTOS: "false"
      GOTIFY_SERVER_SSL_LETSENCRYPT_CACHE: "certs"
      # lists are a little weird but do-able (:
      # GOTIFY_SERVER_SSL_LETSENCRYPT_HOSTS: "- mydomain.tld\n- myotherdomain.tld"
      # GOTIFY_SERVER_RESPONSEHEADERS: 'X-Custom-Header: "custom value"'
      # GOTIFY_SERVER_CORS_ALLOWORIGINS: "- \".+.example.com\"\n- \"otherdomain.com\""
      # GOTIFY_SERVER_CORS_ALLOWMETHODS: "- \"GET\"\n- \"POST\""
      # GOTIFY_SERVER_CORS_ALLOWHEADERS: "- \"Authorization\"\n- \"content-type\""
      # GOTIFY_SERVER_STREAM_ALLOWEDORIGINS: "- \".+.example.com\"\n- \"otherdomain.com\""
      GOTIFY_SERVER_STREAM_PINGPERIODSECONDS: "45"
      GOTIFY_DATABASE_DIALECT: "sqlite3"
      GOTIFY_DATABASE_CONNECTION: "data/gotify.db"
      GOTIFY_PASSSTRENGTH: "10"
      GOTIFY_UPLOADEDIMAGESDIR: "data/images"
      GOTIFY_PLUGINSDIR: "data/plugins"
      GOTIFY_DEFAULTUSER_NAME: "admin"
      GOTIFY_DEFAULTUSER_PASS: "adminadmin"
