# apiVersion: aws.jet.crossplane.io/v1alpha1
# kind: ProviderConfig
# metadata:
#   name: jet-aws
# spec:
#   credentials:
#     source: Secret
#     secretRef:
#       namespace: crossplane-system
#       name: jet-aws-credentials
#       key: credentials
