sablier:
  # -- Annotations for all deployed Deployments
  deploymentAnnotations: {}

  # -- Labels for all deployed Deployments
  deploymentLabels: {}

  # -- Annotations for all deployed pods
  podAnnotations: {}

  # -- Labels for all deployed pods
  podLabels: {}

  # -- Deployment strategy for all deployed Deployments
  deploymentStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

  # -- Sablier's replicas
  replicas: 1

  # -- Sablier log level
  logLevel: "trace"

  image:
    # -- Sablier image repository
    repository: "sablierapp/sablier"

    # -- Sablier image tag
    # (deafult) appVersion
    tag: "1.10.5@sha256:c8ec255212d57708d0fa5d5b76f38e6360b4125efce14f667f28030da112ea94"

  # -- Sablier imagePullPolicy
  imagePullPolicy: IfNotPresent

  # -- Sablier readinessProbe
  readinessProbe:
    httpGet:
      path: /health
      port: 10000
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

  # -- Sablier livenessProbe
  livenessProbe:
    httpGet:
      path: /health
      port: 10000
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

  # -- Resource limits and requests for sablier
  resources: {}
  # requests:
  #   memory: "64Mi"
  #   cpu: "250m"
  # limits:
  #   memory: "128Mi"
  #   cpu: "500m"
