thanos:
  global:
    storageClass: "longhorn"

  image:
    registry: docker.io
    repository: bitnami/thanos
    tag: 0.27.0-scratch-r0

  objstoreConfig: |
    type: "S3"
    config:
      bucket: "thanos"
      endpoint: "thanos-minio:9000"
      access_key: "admin"
      secret_key: "minio123"
      insecure: true

  query:
    enabled: true
    dnsDiscovery:
      enabled: true
      sidecarsService: "prometheus-operated"
      sidecarsNamespace: "monitoring"

    extraFlags:
      - --query.auto-downsampling

    replicaCount: 1

    updateStrategy:
      type: RollingUpdate
    resources:
      limits: {}
      requests: {}

    rbac:
      ##
      create: true

  queryFrontend:
    enabled: true

    config: |
      type: IN-MEMORY
      config:
        max_size: 1GB
        max_size_items: 0
        validity: 0s

    resources:
      limits: {}
      requests: {}

    rbac:
      create: true

    ingress:
      enabled: true
      hostname: thanos.terence.cloud
      ingressClassName: "nginx"
      annotations:
        external-dns.alpha.kubernetes.io/target: terence.cloud
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
      tls: true

    extraEnvVars:
      - name: TZ
        value: Europe/Paris

  bucketweb:
    enabled: true
    ingress:
      enabled: true
      hostname: thanos-bucketweb.terence.cloud
      ingressClassName: "nginx"
      annotations:
        external-dns.alpha.kubernetes.io/target: terence.cloud
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
      tls: true

  compactor:
    enabled: true
    retentionResolutionRaw: 2d
    retentionResolution5m: 30d
    retentionResolution1h: 1y

    persistence:
      enabled: false

  storegateway:
    enabled: true

    persistence:
      enabled: false

  ruler:
    enabled: false

  receive:
    enabled: false

  receiveDistributor:
    enabled: false

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  minio:
    enabled: true
    auth:
      rootUser: admin
      rootPassword: minio123

    defaultBuckets: "thanos"

    persistence:
      size: 25Gi

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/target: terence.cloud
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
      ingressClassName: nginx
      hostname: thanos-minio.terence.cloud
      tls: true
