apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: sablier
spec:
  plugin:
    sablier:
      dynamic:
        displayName: grafana
        refreshFrequency: 5s
        showDetails: true
        theme: shuffle
      sablierUrl: http://sablier-sablier.sablier:10000
      sessionDuration: 10m
      ignoreUserAgent: curl
      group: grafana
