apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
spec:
  type: ExternalName
  externalName: oauth2-proxy.oauth2-proxy
  ports:
    - name: http
      port: 80
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: grafana-oauth2
#   annotations:
#     traefik.ingress.kubernetes.io/router.priority: "100"
# spec:
#   ingressClassName: traefik
#   rules:
#     - host: grafana.terence.cloud
#       http:
#         paths:
#           - path: /oauth2/
#             pathType: Prefix
#             backend:
#               service:
#                 name: oauth2-proxy
#                 port:
#                   number: 80
#   tls:
#     - hosts:
#         - grafana.terence.cloud
#       secretName: grafana-general-tls
